name: Pint

on:
  pull_request:
    types: [opened, reopened, edited, synchronize]

jobs:
  lint:
    name: Pint Check
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php: [8.4]
    steps:
      - name: Checkout step
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: json, dom, curl, libxml, mbstring
          coverage: none

      - name: Install Pint
        run: composer global require laravel/pint

      - name: Run pint
        run: pint -vvv --test
